### ISSUE TITLE
Use Jack

### ISSUE THREAD

**Issue by jaredsburrows** [jaredsburrows/android-gif-example#7]
**Docs:** 
- http://tools.android.com/tech-docs/jackandjill
- https://developer.android.com/guide/platform/j8-jack.html
- http://tools.android.com/knownissues

**Todo:**
- [ ] classpath "com.google.guava:guava:19.0"
  - http://b.android.com/213471 - fix in 2.3
- [ ] Annotation processing bug in `2.3.0-beta1`
  - http://b.android.com/231774
- [x] Get Jacoco working and other coverage plugins working
  - jack does not have `variant.javaCompiler.source`
  - https://android.googlesource.com/platform/prebuilts/sdk/+/master/tools/README-jack-code-coverage.md
- [x] Unit tests pass
- [x] Espresso tests pass
- [x] Test APK runs on API 19 emulator (< API 21)
- [x] Test APK runs on API 21+ emulator

**Other issues that do not prevent this from being merged:**
- Data binding support - http://b.android.com/210615 - fix in 2.3
- Signing config message - http://b.android.com/224293
- Incremental jack compiler - http://b.android.com/224292
- Jack coverage plugin - http://b.android.com/224294 - fix in 2.3
- Lint detector - Use Retrolambda's lombok for now - https://github.com/jaredsburrows/android-gif-example/blob/master/build.gradle

**Comment by jaredsburrows** [comment]
Jack is being deprecated: https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html.
